version: '3.1'
services:
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=budget
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
volumes:
  mongo_data: ~
